routes/web.php
<?php

use App\Http\Controllers\Dashboard\AboutUsContoller as DashboardAboutUsContoller;
use App\Http\Controllers\Dashboard\ArticleController as DashboardArticleController;
use App\Http\Controllers\Dashboard\ContactUsController as DashboardContactUsController;
use App\Http\Controllers\Dashboard\FaqController as DashboardFaqController;
use App\Http\Controllers\Dashboard\HajiController as DashboardHajiController;
use App\Http\Controllers\Dashboard\HajiFurodaController as DashboardHajiFurodaController;
use App\Http\Controllers\Dashboard\HajiKhususController as DashboardHajiKhususController;
use App\Http\Controllers\Dashboard\HajiParentController as DashboardHajiParentController;
use App\Http\Controllers\Dashboard\JejakIslami\NoIncludeController as DashboardJINoIncludeController;
use App\Http\Controllers\Dashboard\JejakIslami\OptionalController as DashboardOptionalController;
use App\Http\Controllers\Dashboard\JejakIslami\ProvitController as DashboardJIProvitController;
use App\Http\Controllers\Dashboard\JejakIslami\SorterJejakIslamiController as DashboardSorterJejakIslamiController;
use App\Http\Controllers\Dashboard\JejakIslami\TripFacilityController as DashboardJITripFacilityController;
use App\Http\Controllers\Dashboard\JejakIslami\TripPlanController as DashboardJITripPlanController;
use App\Http\Controllers\Dashboard\JejakIslamiController as DashboardJejakIslamiController;
use App\Http\Controllers\Dashboard\PacketController as DashboardPacketController;
use App\Http\Controllers\Dashboard\SosialMediaController as DashboardSosialMedia;
use App\Http\Controllers\Dashboard\UmrohCategoryController;
use App\Http\Controllers\Dashboard\UmrohController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Homepage\AboutController;
use App\Http\Controllers\Homepage\ArticleController;
use App\Http\Controllers\Homepage\ContactController;
use App\Http\Controllers\Homepage\FaqController;
use App\Http\Controllers\Homepage\HajiController;
use App\Http\Controllers\Homepage\HajiFurodaController;
use App\Http\Controllers\Homepage\HajiKhususController;
use App\Http\Controllers\Homepage\HomepageController;
use App\Http\Controllers\Homepage\JejakislamiController;
use App\Http\Controllers\Homepage\KeunggulanController;
use App\Http\Controllers\Homepage\MitraController;
use App\Http\Controllers\Homepage\TabunganUmrahController;
use App\Http\Controllers\Homepage\UmrahController;
use App\Http\Controllers\Homepage\UmrahDiamondController;
use App\Http\Controllers\Homepage\UstadController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::prefix('/')->group(function () {
    Route::resource('/', HomepageController::class);
    Route::resource('about', AboutController::class);
    Route::resource('contact', ContactController::class);
    Route::resource('article', ArticleController::class);
    Route::resource('haji-jejak-imani', HajiController::class);
    Route::resource('haji-khusus', HajiKhususController::class);
    Route::resource('haji-furoda', HajiFurodaController::class);
    Route::resource('paket-umrah', UmrahController::class);
    Route::resource('tabungan-umrah', TabunganUmrahController::class);
    Route::resource('jejakislami', JejakislamiController::class);
    Route::resource('keunggulan-jejak-imani', KeunggulanController::class);
    Route::resource('profil-ustadz', UstadController::class);
    Route::resource('umroh-diamond', UmrahDiamondController::class);
    Route::resource('cabang-mitra', MitraController::class);
    Route::get('articel/{slug}', [ArticleController::class, 'view'])->name('article.view');
    Route::get('faq', [FaqController::class, 'index'])->name('faq');
    Route::get('badal-umrah', [UmrahController::class, 'badalUmrah'])->name('badal-umrah');
});

Route::get('cms-admin', function () {
    return redirect('/cms-admin/home');
})->name('auto');
Route::prefix('/cms-admin')->group(function () {
    Auth::routes();

    Route::name("cms.")->group(function () {

        Route::get('/home', [HomeController::class, 'index'])->name('home');
        Route::post('/tinymce-upload', [HomeController::class, 'tinymce_upload'])->name('tinymce.upload');

        Route::resource("umroh", UmrohController::class);
        Route::post('umroh/tracker', [UmrohController::class, 'store_tracker'])->name('umroh.tracker');
        Route::resource("umroh-category", UmrohCategoryController::class);

        // Haji
        Route::prefix('/haji')->name("haji.")->group(function () {
            // Banner
            Route::post("banner", [DashboardHajiController::class, "store_banner"])->name("banner.store");
            Route::delete("banner/{id}", [DashboardHajiController::class, "destroy_banner"])->name("banner.destroy");
            Route::post("label-banner", [DashboardHajiController::class, "store_label_banner"])->name("label.banner.store");
            Route::post("section-1", [DashboardHajiController::class, "store_section_1"])->name("section.1.store");
            Route::post("section-2", [DashboardHajiController::class, "store_section_2"])->name("section.2.store");
            Route::post("section-3", [DashboardHajiController::class, "store_section_3"])->name("section.3.store");
            Route::post("section-4", [DashboardHajiController::class, "store_section_4"])->name("section.4.store");
            Route::post("section-list", [DashboardHajiController::class, "store_section_list"])->name("section.list.store");
            Route::post("section-list-order", [DashboardHajiController::class, "order_section_list"])->name("section.list.order");
            Route::post("haji-content/{id}", [DashboardHajiController::class, "haji_content_store"])->name("content.store");
            Route::delete("section-list/{id}", [DashboardHajiController::class, "destroy_section_list"])->name("section.list.destroy");
            Route::post("testimoni", [DashboardHajiController::class, "store_testimoni"])->name("testimoni.store");
            Route::delete("testimoni/{id}", [DashboardHajiController::class, "destroy_testimoni"])->name("testimoni.destroy");
        });

        // Parent
        Route::prefix('/haji-parent')->name("haji.parent.")->group(function () {
            // Banner
            Route::get("banner", [DashboardHajiParentController::class, "banner"])->name("banner.index");
            Route::get("banner/create", [DashboardHajiParentController::class, "create_banner"])->name("banner.create");
            Route::get("banner/{id}", [DashboardHajiParentController::class, "edit_banner"])->name("banner.edit");

            // Label Banner
            Route::get("label-banner", [DashboardHajiParentController::class, "label_banner"])->name("label.banner.index");

            Route::get("haji-khusus", [DashboardHajiParentController::class, "haji_khusus"])->name("haji_khusus.index");
            Route::get("haji-furoda", [DashboardHajiParentController::class, "haji_furoda"])->name("haji_furoda.index");
            Route::get("testiomni", [DashboardHajiParentController::class, "testimoni"])->name("testimoni.index");
            Route::get("testiomni/create", [DashboardHajiParentController::class, "testimoni_create"])->name("testimoni.create");
            Route::get("testimoni/{id}", [DashboardHajiParentController::class, "testimoni_edit"])->name("testimoni.edit");
        });

        // Khusus
        Route::prefix('/haji-khusus')->name("haji.khusus.")->group(function () {
            // Banner
            Route::get("banner", [DashboardHajiKhususController::class, "banner"])->name("banner.index");
            Route::get("banner/create", [DashboardHajiKhususController::class, "create_banner"])->name("banner.create");
            Route::get("banner/{id}", [DashboardHajiKhususController::class, "edit_banner"])->name("banner.edit");

            // Label Banner
            Route::get("label-banner", [DashboardHajiKhususController::class, "label_banner"])->name("label.banner.index");

            // section 1-4
            Route::get("section-1", [DashboardHajiKhususController::class, "section_1"])->name("section.1.index");
            Route::get("section-2", [DashboardHajiKhususController::class, "section_2"])->name("section.2.index");
            Route::get("section-3", [DashboardHajiKhususController::class, "section_3"])->name("section.3.index");
            Route::get("section-4", [DashboardHajiKhususController::class, "section_4"])->name("section.4.index");

            // section list 1-4 index
            Route::get("section-list-1", [DashboardHajiKhususController::class, "section_list_1"])->name("section.list.1.index");
            Route::get("section-list-2", [DashboardHajiKhususController::class, "section_list_2"])->name("section.list.2.index");
            Route::get("section-list-3", [DashboardHajiKhususController::class, "section_list_3"])->name("section.list.3.index");
            Route::get("section-list-4", [DashboardHajiKhususController::class, "section_list_4"])->name("section.list.4.index");

            // section list 1-4 create
            Route::get("section-list-1/create", [DashboardHajiKhususController::class, "create_section_list_1"])->name("section.list.1.create");
            Route::get("section-list-2/create", [DashboardHajiKhususController::class, "create_section_list_2"])->name("section.list.2.create");
            Route::get("section-list-3/create", [DashboardHajiKhususController::class, "create_section_list_3"])->name("section.list.3.create");

app/Models/Haji.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Haji extends Model
{
    use HasFactory;
    protected $table = 'haji';
}

app/Http/Controllers/Homepage/HajiController.php
<?php

namespace App\Http\Controllers\Homepage;

use App\Http\Controllers\Controller;
use App\Models\Haji;
use Illuminate\Http\Request;

class HajiController extends Controller
{
    private $slug = 'parent'; 

    public function index() {
        $send['other_packet'] = other_packet();
        $send['sosial_media'] = sosial_media();
        $send['banner'] = Haji::where('slug', $this->slug)->where('type', 'banner')->get();        
        $send['label_banner'] = json_decode(Haji::where('slug', $this->slug)->where('type', 'label_banner')->first()->json);
        $send['haji_plus'] = Haji::where('slug', $this->slug)->where('type', 'haji_plus')->first()->json;
        $send['haji_furoda'] = Haji::where('slug', $this->slug)->where('type', 'haji_furoda')->first()->json;
        $send['testimoni'] = Haji::where('slug', $this->slug)->where('type', 'testimoni')->get();
        return view('homepage.haji-jejak-imani', $send);
    }
}

resources/views/dashboard/haji/haji-content/index.blade.php
@extends('layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <!--begin::Container-->
    <div id="kt_content_container" class="container-xxl">
        <!--begin::Card-->
        <div class="card">
            <!--begin::Card header-->
            <div class="card-header border-bottom pt-6">
                <!--begin::Card title-->
                <div class="card-title">
                    <div class="fs-3 fw-bolder">{{ $title }}</div>
                </div>
                <!--end::Card title-->
            </div>
            <!--end::Card header-->
            <!--begin::Card body-->
            <div class="card-body p-5">
                <form class="form w-100" novalidate="novalidate" enctype="multipart/form-data"
                    id="kt_haji_section_2_form" method="POST" action="{{ route('cms.haji.content.store', $data->id) }}">
                    @csrf
                    <input type="hidden" name="id" value="{{ $data->id }}">
                    <input type="hidden" name="slug" value="{{ $slug }}">
                    {{-- begin:Wrapper --}}
                    <div class="row">
                        <input type="hidden" name="slug" value="{{ $slug }}">
                        <input type="hidden" name="type" value="{{ $type }}">
                        <input type="hidden" name="route" value="{{ $route }}">
                        {{-- begin:Row 1 --}}
                        <div class="col-md-12 fv-row mb-10" style="min-height: 300px">
                            <label class="form-label fs-6 fw-bolder text-dark">Deskripsi</label>
                            <textarea name="text" id="mytiny"
                                class="form-control @error('text') is-invalid @enderror">{{ old('text', $data->json) }}</textarea>
                            @error('text')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    {{-- end:Wrapper --}}
                </form>
            </div>
            <!--end::Card body-->
            <div class="card-footer">
                <div class="d-flex justify-content-end">
                    <button type="submit" form="kt_haji_section_2_form" class="btn btn-success ms-2"
                        id="kt_haji_section_2_submit">
                        <span class="indicator-label">Simpan</span>
                        <span class="indicator-progress">Mohon tunggu...
                            <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                    </button>
                </div>
            </div>
        </div>
        <!--end::Card-->
    </div>
    <!--end::Container-->
@endsection

@section('customJS')
    <script src="{{ asset('js/tinymce.min.js') }}"></script>
    <script src="{{ asset('cms/js/custom/dashboard/haji/section-2.js') }}"></script>
    <script>
        tinymce.init({
            selector: '#mytiny',
            plugins: 'print preview paste searchreplace autolink directionality visualblocks visualchars code fullscreen link media pagebreak template codesample charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools colorpicker textpattern help',
            toolbar: 'formatselect | fontsizeselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent | removeformat |',
        });
    </script>
@endsection