routes/web.php
<?php

use App\Http\Controllers\Dashboard\AboutUsContoller as DashboardAboutUsContoller;
use App\Http\Controllers\Dashboard\ArticleController as DashboardArticleController;
use App\Http\Controllers\Dashboard\ContactUsController as DashboardContactUsController;
use App\Http\Controllers\Dashboard\FaqController as DashboardFaqController;
use App\Http\Controllers\Dashboard\HajiController as DashboardHajiController;
use App\Http\Controllers\Dashboard\HajiFurodaController as DashboardHajiFurodaController;
use App\Http\Controllers\Dashboard\HajiKhususController as DashboardHajiKhususController;
use App\Http\Controllers\Dashboard\HajiParentController as DashboardHajiParentController;
use App\Http\Controllers\Dashboard\JejakIslami\NoIncludeController as DashboardJINoIncludeController;
use App\Http\Controllers\Dashboard\JejakIslami\OptionalController as DashboardOptionalController;
use App\Http\Controllers\Dashboard\JejakIslami\ProvitController as DashboardJIProvitController;
use App\Http\Controllers\Dashboard\JejakIslami\SorterJejakIslamiController as DashboardSorterJejakIslamiController;
use App\Http\Controllers\Dashboard\JejakIslami\TripFacilityController as DashboardJITripFacilityController;
use App\Http\Controllers\Dashboard\JejakIslami\TripPlanController as DashboardJITripPlanController;
use App\Http\Controllers\Dashboard\JejakIslamiController as DashboardJejakIslamiController;
use App\Http\Controllers\Dashboard\PacketController as DashboardPacketController;
use App\Http\Controllers\Dashboard\SosialMediaController as DashboardSosialMedia;
use App\Http\Controllers\Dashboard\UmrohCategoryController;
use App\Http\Controllers\Dashboard\UmrohController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Homepage\AboutController;
use App\Http\Controllers\Homepage\ArticleController;
use App\Http\Controllers\Homepage\ContactController;
use App\Http\Controllers\Homepage\FaqController;
use App\Http\Controllers\Homepage\HajiController;
use App\Http\Controllers\Homepage\HajiFurodaController;
use App\Http\Controllers\Homepage\HajiKhususController;
use App\Http\Controllers\Homepage\HomepageController;
use App\Http\Controllers\Homepage\JejakislamiController;
use App\Http\Controllers\Homepage\KeunggulanController;
use App\Http\Controllers\Homepage\MitraController;
use App\Http\Controllers\Homepage\TabunganUmrahController;
use App\Http\Controllers\Homepage\UmrahController;
use App\Http\Controllers\Homepage\UmrahDiamondController;
use App\Http\Controllers\Homepage\UstadController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::prefix('/')->group(function () {
    Route::resource('/', HomepageController::class);
    Route::resource('about', AboutController::class);
    Route::resource('contact', ContactController::class);
    Route::resource('article', ArticleController::class);
    Route::resource('haji-jejak-imani', HajiController::class);
    Route::resource('haji-khusus', HajiKhususController::class);
    Route::resource('haji-furoda', HajiFurodaController::class);
    Route::resource('paket-umrah', UmrahController::class);
    Route::resource('tabungan-umrah', TabunganUmrahController::class);
    Route::resource('jejakislami', JejakislamiController::class);
    Route::resource('keunggulan-jejak-imani', KeunggulanController::class);
    Route::resource('profil-ustadz', UstadController::class);
    Route::resource('umroh-diamond', UmrahDiamondController::class);
    Route::resource('cabang-mitra', MitraController::class);
    Route::get('articel/{slug}', [ArticleController::class, 'view'])->name('article.view');
    Route::get('faq', [FaqController::class, 'index'])->name('faq');
    Route::get('badal-umrah', [UmrahController::class, 'badalUmrah'])->name('badal-umrah');
});

Route::get('cms-admin', function () {
    return redirect('/cms-admin/home');
})->name('auto');
Route::prefix('/cms-admin')->group(function () {
    Auth::routes();

    Route::name("cms.")->group(function () {

        Route::get('/home', [HomeController::class, 'index'])->name('home');
        Route::post('/tinymce-upload', [HomeController::class, 'tinymce_upload'])->name('tinymce.upload');

        Route::resource("umroh", UmrohController::class);
        Route::post('umroh/tracker', [UmrohController::class, 'store_tracker'])->name('umroh.tracker');
        Route::resource("umroh-category", UmrohCategoryController::class);

        // Haji
        Route::prefix('/haji')->name("haji.")->group(function () {
            // Banner
            Route::post("banner", [DashboardHajiController::class, "store_banner"])->name("banner.store");
            Route::delete("banner/{id}", [DashboardHajiController::class, "destroy_banner"])->name("banner.destroy");
            Route::post("label-banner", [DashboardHajiController::class, "store_label_banner"])->name("label.banner.store");
            Route::post("section-1", [DashboardHajiController::class, "store_section_1"])->name("section.1.store");
            Route::post("section-2", [DashboardHajiController::class, "store_section_2"])->name("section.2.store");
            Route::post("section-3", [DashboardHajiController::class, "store_section_3"])->name("section.3.store");
            Route::post("section-4", [DashboardHajiController::class, "store_section_4"])->name("section.4.store");
            Route::post("section-list", [DashboardHajiController::class, "store_section_list"])->name("section.list.store");
            Route::post("section-list-order", [DashboardHajiController::class, "order_section_list"])->name("section.list.order");
            Route::post("haji-content/{id}", [DashboardHajiController::class, "haji_content_store"])->name("content.store");
            Route::delete("section-list/{id}", [DashboardHajiController::class, "destroy_section_list"])->name("section.list.destroy");
            Route::post("testimoni", [DashboardHajiController::class, "store_testimoni"])->name("testimoni.store");
            Route::delete("testimoni/{id}", [DashboardHajiController::class, "destroy_testimoni"])->name("testimoni.destroy");
        });

        // Parent
        Route::prefix('/haji-parent')->name("haji.parent.")->group(function () {
            // Banner
            Route::get("banner", [DashboardHajiParentController::class, "banner"])->name("banner.index");
            Route::get("banner/create", [DashboardHajiParentController::class, "create_banner"])->name("banner.create");
            Route::get("banner/{id}", [DashboardHajiParentController::class, "edit_banner"])->name("banner.edit");

            // Label Banner
            Route::get("label-banner", [DashboardHajiParentController::class, "label_banner"])->name("label.banner.index");

            Route::get("haji-khusus", [DashboardHajiParentController::class, "haji_khusus"])->name("haji_khusus.index");
            Route::get("haji-furoda", [DashboardHajiParentController::class, "haji_furoda"])->name("haji_furoda.index");
            Route::get("testiomni", [DashboardHajiParentController::class, "testimoni"])->name("testimoni.index");
            Route::get("testiomni/create", [DashboardHajiParentController::class, "testimoni_create"])->name("testimoni.create");
            Route::get("testimoni/{id}", [DashboardHajiParentController::class, "testimoni_edit"])->name("testimoni.edit");
        });

        // Khusus
        Route::prefix('/haji-khusus')->name("haji.khusus.")->group(function () {
            // Banner
            Route::get("banner", [DashboardHajiKhususController::class, "banner"])->name("banner.index");
            Route::get("banner/create", [DashboardHajiKhususController::class, "create_banner"])->name("banner.create");
            Route::get("banner/{id}", [DashboardHajiKhususController::class, "edit_banner"])->name("banner.edit");

            // Label Banner
            Route::get("label-banner", [DashboardHajiKhususController::class, "label_banner"])->name("label.banner.index");

            // section 1-4
            Route::get("section-1", [DashboardHajiKhususController::class, "section_1"])->name("section.1.index");
            Route::get("section-2", [DashboardHajiKhususController::class, "section_2"])->name("section.2.index");
            Route::get("section-3", [DashboardHajiKhususController::class, "section_3"])->name("section.3.index");
            Route::get("section-4", [DashboardHajiKhususController::class, "section_4"])->name("section.4.index");

            // section list 1-4 index
            Route::get("section-list-1", [DashboardHajiKhususController::class, "section_list_1"])->name("section.list.1.index");
            Route::get("section-list-2", [DashboardHajiKhususController::class, "section_list_2"])->name("section.list.2.index");
            Route::get("section-list-3", [DashboardHajiKhususController::class, "section_list_3"])->name("section.list.3.index");
            Route::get("section-list-4", [DashboardHajiKhususController::class, "section_list_4"])->name("section.list.4.index");

            // section list 1-4 create
            Route::get("section-list-1/create", [DashboardHajiKhususController::class, "create_section_list_1"])->name("section.list.1.create");
            Route::get("section-list-2/create", [DashboardHajiKhususController::class, "create_section_list_2"])->name("section.list.2.create");
            Route::get("section-list-3/create", [DashboardHajiKhususController::class, "create_section_list_3"])->name("section.list.3.create");

app/Http/Controllers/Dashboard/ArticleController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class ArticleController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $send['auth'] = Auth::user();
        $send['title'] = "Artikel";
        $send['data'] = Article::get();
        return view('dashboard.article.index', $send);
    }

    public function create()
    {
        $send['auth'] = Auth::user();
        $send['title'] = "Tambah Artikel";
        return view('dashboard.article.create', $send);
    }

    public function store(Request $request)
    {
        $image = $request->file("image");
        $imageName = 'upload/article/' . nameFile($image);

        try {
            DB::beginTransaction();
            $data = new Article;
            $image->move(public_path('upload/article'), $imageName);
            $data->name = $request->name;
            $data->slug = strtolower(str_replace(" ", "_", $request->slug)) ?? strtolower(str_replace(" ", "_", $request->name));
            $data->image = $imageName;
            $data->json = $request->text;
            $data->save();
            DB::commit();
            return redirect()->route('cms.article.index')
                ->with("success", "Tambah Artikel Berhasil");
        } catch (\Exception $e) {
            DB::rollback();
            throw $e;
            /* Transaction failed. */
            Session::flash('error', 'Terjadi kesalahan saat menyimpan data');
            return redirect()->back()
                ->withInput($request->all());
        }
    }

    public function edit($id)
    {
        $send['auth'] = Auth::user();
        $send['title'] = "Perbarui Artikel";
        $send['data'] = Article::where('id', $id)->first();
        return view('dashboard.article.edit', $send);
    }

    public function update(Request $request)
    {

        $data = Article::where("id", $request->id)->first();
        if (!$data) {
            Session::flash('warning', 'Data tidak ditemukan');
            return redirect()->back()
                ->withInput($request->all());
        }
        $image = $request->file("image");
        $imageName = $data->image;
        if ($image) {
            $imageName = 'upload/article/' . nameFile($image);
        }

        try {
            DB::beginTransaction();
            if ($image) {
                deletedFile($data->image);                
                $image->move(public_path('upload/article'), $imageName);
            }
            $data->name = $request->name;
            $data->slug = strtolower(str_replace(" ", "_", $request->slug)) ?? strtolower(str_replace(" ", "_", $request->name));
            $data->image = $imageName;
            $data->json = $request->text;
            $data->save();
            DB::commit();
            return redirect()->route('cms.article.index')
                ->with("success", "Tambah Artikel Berhasil");
        } catch (\Exception $e) {
            DB::rollback();
            // throw $e;
            /* Transaction failed. */
            Session::flash('error', 'Terjadi kesalahan saat menyimpan data');
            return redirect()->back()
                ->withInput($request->all());
        }
    }

    public function destroy(Request $request)
    {
        $data = Article::where("id", $request->id)->first();
        if (!$data) {
            Session::flash('warning', 'Data tidak ditemukan');
            http_response_code(400);
        }

        try {
            DB::beginTransaction();
            deletedFile($data->image);
            $data->delete();
            DB::commit();
            http_response_code(200);
        } catch (\Throwable $th) {
            //throw $th;
            Session::flash('eror', 'Terjadi kesalahan');
            http_response_code(400);
            DB::rollBack();
        }
    }
}

app/Http/Controllers/Dashboard/JejakIslami/OptionalController.php
<?php

namespace App\Http\Controllers\Dashboard\JejakIslami;

use App\Http\Controllers\Controller;
use App\Models\Content;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class OptionalController extends Controller
{
    private $slug = "jejak-islami";
    private $type = "optional";
    private $title = "Opsional - Jejak Islami";
    private $route = "cms.content.jejak.islami.optional";

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $send['auth'] = Auth::user();
        $send['title'] = $this->title;
        $send['data'] = Content::where("slug", $this->slug)->where('type', $this->type)->first();
        return view('dashboard.content.jejak-islami.optional.index', $send);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $data = Content::where("slug", $this->slug)->where('type', $this->type)->first();

        if (!$data) {
            Session::flash('warning', 'Data tidak ada ditemukan');
            return redirect()->back()
                ->withInput($request->all());
        }

        try {
            DB::beginTransaction();            
            $data->json = $request->text;
            $data->save();
            DB::commit();
            Session::flash("success", "Perbarui " . $this->title . " Berhasil");
            return redirect()->route($this->route . '.index');
        } catch (\Throwable $th) {
            DB::rollBack();
            // throw $th;
            Session::flash('error', 'Terjadi kesalahan saat menyimpan data');
            return redirect()->back()
                ->withInput($request->all());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Content::where('slug', $this->slug)->where('type', $this->type)->where("id", $id)->first();

        if (!$data) {
            Session::flash('warning', 'Data tidak ada ditemukan');
            http_response_code(400);
        }

        try {
            DB::beginTransaction();
            $data->delete();
            DB::commit();
            http_response_code(200);
        } catch (\Throwable $th) {
            DB::rollBack();
            // throw $th;
            Session::flash('error', 'Terjadi kesalahan saat menyimpan data');
            http_response_code(400);
        }
    }
}

resources/views/dashboard/umroh category/index.blade.php
@extends('layouts.app')

@section('title')
{{$title}}
@endsection

@section('content')
<!--begin::Card-->
<div class="card">
    <!--begin::Card header-->
    <div class="card-header border-0 pt-6">
        <!--begin::Card title-->
        <div class="card-title">
            <!--begin::Search-->
            <div class="d-flex align-items-center position-relative my-1">
                <i class="bi bi-search fs-5 position-absolute ms-6"></i>
                <!--end::Svg Icon-->
                <input type="text" data-kt-category-table-filter="search"
                    class="form-control form-control-solid w-250px ps-15" placeholder="Cari Category" />
            </div>
            <!--end::Search-->
        </div>
        <!--begin::Card title-->
        <div class="card-toolbar">
            <!--begin::Toolbar-->
            <div class="d-flex justify-content-end" data-kt-category-table-toolbar="base">
                <!--begin::Add category-->
                <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                    data-bs-target="#createModal">Tambah</button>
                <!--end::Add category-->
            </div>
        </div>
        <!--end::Card toolbar-->
    </div>
    <!--end::Card header-->
    <!--begin::Card body-->
    <div class="card-body pt-0">
        <!--begin::Table-->
        <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_categorys_table">
            <!--begin::Table head-->
            <thead>
                <!--begin::Table row-->
                <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0 cursor-pointer">
                    <th class="min-w-10px pe-2">
                        No
                    </th>
                    <th class="min-w-125px">Nama</th>
                    <th class="min-w-125px">Deskripsi</th>
                    <td class="d-none">ID</td>
                    <th class="text-end min-w-70px">Actions</th>
                </tr>
                <!--end::Table row-->
            </thead>
            <!--end::Table head-->
            <!--begin::Table body-->
            <tbody class="fw-bold text-gray-600">
                @foreach ($data as $value => $item)
                <tr>
                    <td> {{$value+1}} </td>
                    <td> {{$item->name}} </td>
                    <td> {!!$item->text!!} </td>
                    <td class="d-none"> {{$item->id}} </td>
                    <td class="text-end">
                        <div class="btn-group" role="group">
                            <button type="button" class="btn btn-warning" data-bs-toggle="modal"
                                data-kt-category-table-filter="edit_row" data-bs-target="#editModal">Ubah</button>
                            <button type="button" class="btn btn-danger" data-kt-category-table-filter="delete_row"
                                data-id=" {{$item->id}} " data-token="{{ csrf_token() }}">Hapus</button>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <!--end::Table body-->
        </table>
        <!--end::Table-->
    </div>
    <!--end::Card body-->
</div>
<!--end::Card-->

<!-- Modal Create -->
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Kategori</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="form w-100" novalidate="novalidate" id="kt_category_umroh_create_form" method="POST"
                    action="{{ route('cms.umroh-category.store') }}">
                    @csrf
                    <div class="row">
                        <div class="col-md-12 fv-row">
                            <label class="form-label fs-6 fw-bolder text-dark">Judul</label>
                            <input type="text"
                                class="form-control form-control w-100 @error('name') is-invalid @enderror" name="name"
                                value="" required autofocus />
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-md-12 fv-row mb-10" style="min-height: 300px">
                            <label class="form-label fs-6 fw-bolder text-dark">Deskripsi</label>
                            <textarea name="text"
                                class="form-control mytiny @error('text') is-invalid @enderror"></textarea>
                            @error('text')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="close-create-modal"
                    data-bs-dismiss="modal">Tutup</button>
                <button type="submit" form="kt_category_umroh_create_form" id="submit-create-modal"
                    class="btn btn-primary">
                    <span class="indicator-label">Simpan</span>
                    <span class="indicator-progress">Mohon Tunggu...
                        <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Edit -->
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Perbaharui Kategori</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="form w-100" novalidate="novalidate" enctype="multipart/form-data"
                    id="kt_category_umroh_edit_form" method="POST" action="{{ route('cms.umroh-category.store') }}">
                    @csrf
                    <input name="_method" type="hidden" value="PUT">
                    <input name="id" type="hidden" id="id-edit" value="">
                    <div class="row">
                        <div class="col-md-12 fv-row">
                            <label class="form-label fs-6 fw-bolder text-dark">Judul</label>
                            <input type="text" id="name-edit"
                                class="form-control form-control w-100 @error('name') is-invalid @enderror" name="name"
                                value="" required autofocus />
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-md-12 fv-row mb-10" style="min-height: 300px">
                            <label class="form-label fs-6 fw-bolder text-dark">Deskripsi</label>
                            <textarea name="text" id="text-edit"
                                class="form-control mytiny @error('text') is-invalid @enderror"></textarea>
                            @error('text')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="close-edit-modal"
                    data-bs-dismiss="modal">Tutup</button>
                <button type="submit" form="kt_category_umroh_edit_form" id="submit-edit-modal" class="btn btn-primary">
                    <span class="indicator-label">Update</span>
                    <span class="indicator-progress">Mohon Tunggu...
                        <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                </button>
            </div>
        </div>
    </div>
</div>
@endsection

@section('customJS')
<script src="{{asset('cms/js/custom/dashboard/umroh category/index.js')}}"></script>
<script src="{{asset('cms/plugins/custom/datatables/datatables.bundle.js')}}"></script>
<script src="{{asset('js/tinymce.min.js')}}"></script>
<script>
    tinymce.init({
      selector: '#text-edit',
      plugins: 'print preview paste searchreplace autolink directionality visualblocks visualchars code fullscreen link media pagebreak template codesample charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools colorpicker textpattern help',
      toolbar: 'formatselect | fontsizeselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent | removeformat |',
    });
</script>
@endsection